- src/api/controllers/client.controller.js
- src/api/repositories/client.repository.js
- src/api/services/client.service.js
브랜치 변경되있는걸 잊고 group 브랜치에서 작업했습니다..다음엔 확인하겠습니다.
> fix: 클라이언트 정보 수정 시 clientName, contact 변경 가능하게 수정

- src/api/services/user.service.js
- src/db/migrations/20230314090155-create-companies.js
- src/db/models/companies.js
userService.함수명 지정 에러 수정 , companyEamil  컬럼 추가, 기타 코드 간단 수정
> Feature/customer: 에러수정

- src/api/controllers/user.controller.js
- src/api/repositories/company.repository.js
- src/api/repositories/user.repository.js
- src/api/routes/user.route.js
- src/api/services/user.service.js
간단한 코드 수정 몇개와 user router에 delete 추가 되었습니다. 
에러 때문에 작성했던 delete 를 모두 다시 작성한거라 회원 정보 수정은 오늘 중으로 다시 pr 올리겠습니다
> Feature/customer : 코드 수정, router/delete  추가

- src/api/controllers/user.controller.js
- src/api/repositories/company.repository.js
- src/api/repositories/user.repository.js
- src/api/services/user.service.js
Feature/customer : 이메일 중복 검사 수정, editUser 코드 리팩토링, create companyEmail 추가 하였습니다
> Feature/customer : 이메일 중복 검사 수정, editUser 코드 리팩토링

- src/api/controllers/user.controller.js
- src/middlewares/auth.middleware.js
authorization > Authorization 대문자로 통일 시켰습니다
> Feature/customer : 간단한 코드 수정입니다

- src/api/controllers/client.controller.js
- src/api/repositories/client.repository.js
- src/api/routes/client.route.js
- src/api/services/client.service.js
- src/db/models/client.js
- src/db/models/groups.js
- src/helpers/parse.sequelize.js
- 클라이언트 전체 조회 API - 그룹 정보 표시
- 클라이언트 그룹별 조회 API  - 로직 구현
> feat: 클라이언트 조회 API 수정 , 그룹별 조회 API 구현

- src/api/controllers/user.controller.js
- src/api/services/user.service.js
userController/userService.getUser 예외처리 코드 추가 먼저 PR 드립니다!
> Feature/customer : userController/userService.getUser 예외처리 코드 추가

- src/api/controllers/clientGroup.controller.js
- src/api/routes/clientGroup.route.js
- src/api/services/clientGroup.service.js
> feat: 클라이언트 그룹 이동

- package-lock.json
- package.json
- src/api/controllers/user.controller.js
- src/api/services/user.service.js
userController, userService 예외처리 및 유효성 검증 코드추가 되었습니다 
추가된 예외처리, 유효성 검증 기준으로 로컬에서 테스트는 완료 되었으며
추가적인 예외처리 나 유효성 검증들은 지속적으로 고민 후 추가 할 예정입니다 
부족한 점  피드백 주시면 바로 반영 하겠습니다
> Feature/customer : userController, userService 예외처리 및 유효성 검증 코드추가

- src/api/controllers/user.controller.js
userController.loginUser 토큰 쿠키 > 헤더로 변경되었으며, 쿠키 전달 삭제로 쿠키 만료 시간 설정 값 또한 삭제 되었습니다
> Feature/customer : userController.loginUser 토큰 쿠키 > 헤더로 변경

- src/api/controllers/user.controller.js
userController.loginUser 토큰 쿠키전송 > 헤더 전송 변경, 쿠키 만료 시간 설정 삭제
> Feature/customer : userController.loginUser 토큰 쿠키전송 > 헤더 전송 변경, 쿠키 만료 시간 설정 삭제

- src/api/controllers/user.controller.js
Feature/customer: userController 이메일 유효성 검증 정규표현식 변경되었습니다
기존에는 @ 앞 아이디가 무조건 영문 숫자 포함이었으나, 그 부분을 제외하고 이메일 형식만 검증 되도록 변경하였습니다
> Feature/customer: userController 이메일 유효성 검증 정규표현식 변경

- src/middlewares/auth.middleware.js
요청 시 토큰값을 req.cookie 로 받아오던 코드를 req.headers 로 변경하였습니다
> fix: auth.middleware req.cookie > req.headers 변경

- src/api/services/user.service.js
userService try/catch 에러핸들링 추가 후 커밋 입니다
> Feature/customer : userService try/catch 에러핸들링 추가 후 커밋

- src/middlewares/auth.middleware.js
에러 코드 수정 입니다 Authorization  > authorization
> fix: auth.middleware 에러 코드 수정 Authorization  > authorization

- src/middlewares/auth.middleware.js
auth.middleware 토큰 없거나, 일치하지 않는 경우 예외처리 코드 수정 했습니다
> fix: auth.middleware 토큰 없거나, 일치하지 않는 경우 예외처리 코드 수정

- src/controllers/user.controller.js
- src/routes/user.route.js
Feature/customer : userController 유효성 검증 삭제 및 JoiHelper 미들웨어 적용입니다
> Feature/customer : userController 유효성 검증 삭제 및 JoiHelper 미들웨어 적용

- package-lock.json
- package.json
- src/controllers/user.controller.js
- src/routes/user.route.js
Feature/customer: npx lodash 라이브러리 삭제, user.route joiHelper 추가 및 수정, userController 불필요한 코드 삭제
> Feature/customer: npx lodash 라이브러리 삭제, user.route joiHelper 추가 및 수정, userController 불필요한 코드 삭제

- src/db/migrations/20230318081642-create-talk-contents.js
- src/repositories/client.repository.js
- src/services/client.service.js
테스트 해봤을 때 그룹명 외에는 검색됩니다. 그룹명도 검색 대상에 넣고 싶은데 어제서부터 해봐도 모르겠습니다.
> fix: 클라이언트, 그룹별 클라이언트 검색 수정

- src/routes/user.route.js
- 참고자료 : 공식문서 (https://github.com/BRIKEV/express-jsdoc-swagger)
> feat: Swagger User Routes example 추가

- src/repositories/group.repository.js
- src/repositories/user.repository.js
- src/services/clientGroup.service.js
브랜치에 문제 생겨서 다시 확인하느라 오래걸렸습니다. 확인 부탁드려요!
> fix: 다건 등록시 미지정 그룹 자동 저장
